trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore AzureWebApp.slnx
  displayName: Restore

- script: dotnet build AzureWebApp.slnx --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish AzureWebApp.slnx --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'